language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.2
  - android-27
  - extra-android-m2repository
  - extra-android-support
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_install:
- gem install fir-cli
- yes | sdkmanager "platforms;android-27"
- openssl aes-256-cbc -K $encrypted_5c3ae9008f8a_key -iv $encrypted_5c3ae9008f8a_iv
  -in cxz.jks.enc -out cxz.jks -d
- rm -f gradle.properties
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
